<?php
/**
 * Prevent production-derived snapshot data from causing external side effects.
 *
 * This file is mounted only in the private snapshot environment. It is not part
 * of the Presenter release package.
 *
 * @package Presenter
 */

declare( strict_types=1 );

/**
 * Resolve an approved request origin for browser access to the snapshot.
 *
 * The web container is reachable on the private network, but arbitrary Host
 * headers must not influence generated URLs. Only loopback or RFC 1918 IPv4
 * hosts on the snapshot web port are accepted.
 *
 * @return string|null Approved origin, or null outside an HTTP request.
 */
function presenter_snapshot_request_origin(): ?string {
	if ( ! isset( $_SERVER['HTTP_HOST'] ) || ! is_string( $_SERVER['HTTP_HOST'] ) ) {
		return null;
	}

	$host = strtolower( trim( wp_unslash( $_SERVER['HTTP_HOST'] ) ) );
	$url  = wp_parse_url( 'http://' . $host );

	if ( ! is_array( $url ) || 8890 !== ( $url['port'] ?? null ) ) {
		return null;
	}

	$hostname      = strtolower( (string) ( $url['host'] ?? '' ) );
	$approved_host = in_array(
		$hostname,
		array( 'localhost', '127.0.0.1', '[::1]' ),
		true
	);
	if ( ! $approved_host && false !== filter_var( $hostname, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4 ) ) {
		$approved_host =
			str_starts_with( $hostname, '10.' ) ||
			str_starts_with( $hostname, '192.168.' ) ||
			1 === preg_match( '/^172\.(?:1[6-9]|2\d|3[01])\./D', $hostname );
	}

	if ( ! $approved_host ) {
		return null;
	}

	return 'http://' . $host;
}

/**
 * Use the approved request origin for URLs generated by WordPress.
 *
 * @param mixed $stored_origin Stored home or site URL.
 * @return mixed Request origin when approved; the stored value otherwise.
 */
function presenter_snapshot_filter_request_origin( $stored_origin ) {
	return presenter_snapshot_request_origin() ?? $stored_origin;
}
add_filter( 'option_home', 'presenter_snapshot_filter_request_origin' );
add_filter( 'option_siteurl', 'presenter_snapshot_filter_request_origin' );

/**
 * Rewrite snapshot-local absolute URLs for an approved private-network host.
 *
 * @param string $content Rendered post content.
 * @return string Content using the current approved request origin.
 */
function presenter_snapshot_rewrite_request_origin( string $content ): string {
	$origin = presenter_snapshot_request_origin();

	if ( null === $origin ) {
		return $content;
	}

	$stored_origin  = 'http://localhost:8890';
	$escaped_origin = str_replace( '/', '\\/', $stored_origin );

	return str_replace(
		array(
			$stored_origin,
			$escaped_origin,
			rawurlencode( $stored_origin ),
		),
		array(
			$origin,
			str_replace( '/', '\\/', $origin ),
			rawurlencode( $origin ),
		),
		$content
	);
}
add_filter( 'plugins_url', 'presenter_snapshot_rewrite_request_origin', PHP_INT_MAX );
add_filter( 'content_url', 'presenter_snapshot_rewrite_request_origin', PHP_INT_MAX );
add_filter( 'the_content', 'presenter_snapshot_rewrite_request_origin', PHP_INT_MAX );

/**
 * Rewrite remaining snapshot-local URLs in HTML and REST responses.
 */
function presenter_snapshot_start_request_origin_rewrite(): void {
	$origin = presenter_snapshot_request_origin();
	if ( null !== $origin && 'http://localhost:8890' !== $origin ) {
		ob_start( 'presenter_snapshot_rewrite_request_origin' );
	}
}
add_action( 'muplugins_loaded', 'presenter_snapshot_start_request_origin_rewrite', 0 );

/**
 * Treat mail as successfully handled without sending it.
 */
add_filter( 'pre_wp_mail', '__return_true' );

/**
 * Block server-side HTTP except for explicitly local destinations.
 *
 * @param false|array|WP_Error $response Preemptive response.
 * @param array                $arguments Request arguments.
 * @param string               $url       Request URL.
 * @return false|array|WP_Error
 */
function presenter_snapshot_preempt_http_request( $response, array $arguments, string $url ) {
	unset( $arguments );

	$host          = wp_parse_url( $url, PHP_URL_HOST );
	$allowed_hosts = array( 'localhost', '127.0.0.1', '::1' );

	if ( is_string( $host ) && in_array( strtolower( $host ), $allowed_hosts, true ) ) {
		return $response;
	}

	return new WP_Error(
		'presenter_snapshot_external_request_blocked',
		__( 'External HTTP is disabled in the Presenter snapshot environment.', 'presenter' )
	);
}
add_filter( 'pre_http_request', 'presenter_snapshot_preempt_http_request', 10, 3 );

/**
 * Prevent indexing and browser-side calls to production services.
 */
function presenter_snapshot_send_safety_headers(): void {
	if ( headers_sent() ) {
		return;
	}

	header( 'X-Robots-Tag: noindex, nofollow, noarchive', true );
	header(
		// Reveal.js 4's UMD build requires eval; this policy is snapshot-only and
		// still prevents scripts, connections, and media from external hosts.
		"Content-Security-Policy: default-src 'self'; base-uri 'self'; connect-src 'self'; font-src 'self' data:; frame-src 'self'; img-src 'self' data: blob:; media-src 'self' blob:; object-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; worker-src 'self' blob:;",
		true
	);
}
add_action( 'send_headers', 'presenter_snapshot_send_safety_headers' );

/**
 * Replace historical external chart library URLs with snapshot-local assets.
 *
 * The production-derived decks contain these exact script URLs in their saved
 * HTML. Rewriting only the matching script src attributes keeps the snapshot's
 * restrictive CSP intact without changing deck content or production behavior.
 *
 * @param string $html Complete slideshow response HTML.
 * @return string
 */
function presenter_snapshot_rewrite_chart_script_urls( string $html ): string {
	$script_urls = array(
		'https://www.gstatic.com/charts/loader.js' => '/wp-content/presenter-snapshot-assets/google-charts/loader.js',
		'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.5.1/chart.min.js' => '/wp-content/presenter-snapshot-assets/chart.js/3.5.1/chart.min.js',
	);

	if ( ! class_exists( 'WP_HTML_Tag_Processor' ) ) {
		return $html;
	}

	$processor = new WP_HTML_Tag_Processor( $html );

	while ( $processor->next_tag( array( 'tag_name' => 'script' ) ) ) {
		$source = $processor->get_attribute( 'src' );

		if ( is_string( $source ) && isset( $script_urls[ $source ] ) ) {
			$processor->set_attribute( 'src', $script_urls[ $source ] );
		}
	}

	return $processor->get_updated_html();
}

/**
 * Start rewriting the final response only for slideshow front-end requests.
 */
function presenter_snapshot_start_chart_script_rewrite(): void {
	if ( ! is_singular( 'slideshow' ) ) {
		return;
	}

	ob_start( 'presenter_snapshot_rewrite_chart_script_urls' );
}
add_action( 'template_redirect', 'presenter_snapshot_start_chart_script_rewrite', 0 );

add_filter( 'wp_sitemaps_enabled', '__return_false' );
