Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 80, host: 80

  config.vm.provision "shell", inline: <<-SHELL
    # Install Dependencies
    apt-get update
    apt-get install -y apache2 libapache2-mod-fcgid php-fpm mysql-server php-mysql git
    # Set up Apache
    a2enmod proxy_fcgi setenvif
    a2enconf php7.2-fpm
    systemctl restart apache2
    # Set up Wordpress
    /vagrant/root_install_wordpress.sh
  SHELL
end
