<?php
/**
 * Presenter 2.0 asset registration.
 *
 * @package Presenter
 */

namespace Presenter;

/**
 * Registers built front-end assets without loading them on ordinary requests.
 */
final class Assets implements Hook_Provider {
	/**
	 * Plugin context.
	 *
	 * @var Plugin_Context
	 */
	private Plugin_Context $context;

	/**
	 * Create the asset registry.
	 *
	 * @param Plugin_Context $context Plugin context.
	 */
	public function __construct( Plugin_Context $context ) {
		$this->context = $context;
	}

	/**
	 * Register WordPress hooks.
	 */
	public function register_hooks(): void {
		add_action( 'init', array( $this, 'register' ), 5 );
	}

	/**
	 * Register modern presentation and block editor assets.
	 */
	public function register(): void {
		$frontend_asset = $this->metadata( 'frontend' );
		$editor_asset   = $this->metadata( 'index' );

		wp_register_script(
			'presenter-frontend',
			$this->context->url() . 'build/frontend.js',
			$frontend_asset['dependencies'],
			$frontend_asset['version'],
			array(
				'in_footer' => true,
				'strategy'  => 'defer',
			)
		);
		wp_register_script(
			'presenter-block-editor',
			$this->context->url() . 'build/index.js',
			$editor_asset['dependencies'],
			$editor_asset['version'],
			array( 'in_footer' => true )
		);
		wp_register_style(
			'presenter-reveal-6',
			$this->context->url() . 'build/reveal/reveal.css',
			array(),
			$this->context->version()
		);
	}

	/**
	 * Enqueue the modern presentation runtime and selected theme.
	 *
	 * @param string $theme_stylesheet_url Selected presentation theme URL.
	 */
	public function enqueue_presentation( string $theme_stylesheet_url ): void {
		$this->register();

		wp_enqueue_script( 'presenter-frontend' );
		wp_enqueue_style( 'presenter-reveal-6' );
		wp_deregister_style( 'reveal-theme' );
		wp_register_style(
			'reveal-theme',
			$theme_stylesheet_url,
			array( 'presenter-reveal-6' ),
			$this->context->version()
		);
		wp_enqueue_style( 'reveal-theme' );
	}

	/**
	 * Read the dependency metadata generated by wp-scripts.
	 *
	 * @param string $entrypoint Build entrypoint name.
	 * @return array{dependencies: array<int, string>, version: string} Asset metadata.
	 */
	private function metadata( string $entrypoint ): array {
		$metadata_file = $this->context->directory() . '/build/' . $entrypoint . '.asset.php';

		if ( ! is_readable( $metadata_file ) ) {
			return array(
				'dependencies' => array(),
				'version'      => $this->context->version(),
			);
		}

		$metadata = require $metadata_file;

		if ( ! is_array( $metadata ) ) {
			return array(
				'dependencies' => array(),
				'version'      => $this->context->version(),
			);
		}

		return array(
			'dependencies' => array_values( $metadata['dependencies'] ?? array() ),
			'version'      => (string) ( $metadata['version'] ?? $this->context->version() ),
		);
	}
}
